# Generated by Django 6.0.6 on 2026-06-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '联系表单', 'verbose_name_plural': '联系表单'},
        ),
    ]
