# Generated by Django 6.0.6 on 2026-06-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_contract_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('briefing', '活动简报'), ('preview', '活动预告')], max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('date', models.DateField(verbose_name='活动日期')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('author', models.CharField(max_length=50, verbose_name='提交人')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已公开'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='公开时间')),
            ],
            options={
                'verbose_name': '活动档案',
                'verbose_name_plural': '活动档案',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('tag', models.CharField(blank=True, max_length=30, verbose_name='标签')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已公开'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='公开时间')),
            ],
            options={
                'verbose_name': '论坛帖子',
                'verbose_name_plural': '论坛帖子',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=80, verbose_name='主题')),
                ('body', models.TextField(verbose_name='内容')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '不公开')], default='public', max_length=20, verbose_name='公开方式')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('reply', models.TextField(blank=True, verbose_name='社团回复')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
            ],
            options={
                'verbose_name': '社团信箱',
                'verbose_name_plural': '社团信箱',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('body', models.TextField(verbose_name='内容')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='club.forumcomment', verbose_name='回复对象')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='club.forumpost', verbose_name='所属帖子')),
            ],
            options={
                'verbose_name': '论坛留言',
                'verbose_name_plural': '论坛留言',
                'ordering': ['created_at'],
            },
        ),
    ]
